version: '3'

services:
  money_mastery_db:
    image: postgres
    container_name: money-mastery-db
    ports:
      - '5430:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data

  app:
    build: .
    container_name: money-mastery-api
    ports:
      - "8008:3005"
    volumes:
      - ".:/app"
    depends_on:
      - money_mastery_db

volumes:
    data:
